-- ROLLBACK of A3 · do NOT place in supabase/migrations
-- Source: Vault 01_BRIEFS_SENT/MASTER_SPEC_Commerce_Hub_PhaseA_2026-09-29.md (section 6)
-- Generated by Alich from the spec text (byte-copy, no retyping) · run by พี่หยัด only (G4)
-- Rollback: none needed
BEGIN;
SET LOCAL lock_timeout = '3s';

-- 1) restore original function bodies (baseline 2026-09-27)
CREATE OR REPLACE FUNCTION public.checkout_order(p_order_id uuid) RETURNS jsonb
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    v_player_id       UUID;
    v_status          VARCHAR;
    v_total_ap        INTEGER;
    v_expires_at      TIMESTAMPTZ;
    v_caller          UUID := public.current_player_id();
    v_move_result     JSONB;
    r_item            RECORD;
    v_store_type      VARCHAR;
    v_eq_type         VARCHAR;
    v_fulfilled_count INTEGER := 0;
    v_balance_after   NUMERIC;
BEGIN
    SELECT player_id, status, total_price_ap, expires_at
    INTO v_player_id, v_status, v_total_ap, v_expires_at
    FROM public.orders
    WHERE id = p_order_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'ORDER_NOT_FOUND';
    END IF;

    -- v_caller IS NULL = ไม่มี auth session (เรียกจาก webhook/service-role) ปล่อยผ่าน
    IF v_caller IS NOT NULL AND v_caller IS DISTINCT FROM v_player_id AND NOT public.is_admin() THEN
        RAISE EXCEPTION 'FORBIDDEN';
    END IF;

    IF v_status <> 'PENDING' THEN
        RAISE EXCEPTION 'ORDER_NOT_PENDING';
    END IF;

    IF v_expires_at < NOW() THEN
        RAISE EXCEPTION 'ORDER_EXPIRED';
    END IF;

    IF v_total_ap > 0 THEN
        v_move_result := public.move_ap(
            v_player_id, -v_total_ap, 'STORE_REDEEM',
            'checkout-order-' || p_order_id::text, 'order', p_order_id
        );

        IF NOT (v_move_result->>'success')::boolean THEN
            IF v_move_result->>'error' = 'INSUFFICIENT_AP_BALANCE' THEN
                RAISE EXCEPTION 'INSUFFICIENT_AP';
            ELSIF v_move_result->>'error' = 'DUPLICATE_KEY' THEN
                RAISE EXCEPTION 'ORDER_NOT_PENDING';
            ELSE
                RAISE EXCEPTION '%', v_move_result->>'error';
            END IF;
        END IF;

        v_balance_after := (v_move_result->>'balance_after')::numeric;
    END IF;

    FOR r_item IN
        SELECT variant_id, quantity, name_at FROM public.order_items WHERE order_id = p_order_id
    LOOP
        UPDATE public.store_item_variants
        SET stock = stock - r_item.quantity,
            reserved_stock = reserved_stock - r_item.quantity
        WHERE id = r_item.variant_id;

        SELECT i.type INTO v_store_type
        FROM public.store_items i
        JOIN public.store_item_variants v ON v.item_id = i.id
        WHERE v.id = r_item.variant_id;

        IF v_store_type = 'DIGITAL' THEN
            v_eq_type := 'FRAME';
            IF POSITION('badge' IN LOWER(r_item.name_at)) > 0 THEN
                v_eq_type := 'BADGE';
            ELSIF POSITION('title' IN LOWER(r_item.name_at)) > 0 THEN
                v_eq_type := 'TITLE';
            END IF;

            INSERT INTO public.player_inventory (player_id, variant_id, item_type, is_equipped, quantity)
            VALUES (v_player_id, r_item.variant_id, v_eq_type, FALSE, r_item.quantity)
            ON CONFLICT (player_id, variant_id) DO UPDATE
                SET quantity = public.player_inventory.quantity + EXCLUDED.quantity;

        ELSIF v_store_type = 'PHYSICAL' THEN
            INSERT INTO public.shipments (order_id, status)
            VALUES (p_order_id, 'PENDING');
        END IF;

        v_fulfilled_count := v_fulfilled_count + 1;
    END LOOP;

    UPDATE public.orders SET status = 'PAID' WHERE id = p_order_id;

    IF v_balance_after IS NULL THEN
        SELECT ap_balance INTO v_balance_after FROM public.players WHERE id = v_player_id;
    END IF;

    RETURN jsonb_build_object(
        'success', true,
        'order_id', p_order_id,
        'status', 'PAID',
        'fulfilled_items_count', v_fulfilled_count,
        'ap_deducted', v_total_ap,
        'remaining_balance', COALESCE(v_balance_after, 0)
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.settle_payment_intent(p_payment_intent_id uuid) RETURNS jsonb
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    v_intent          RECORD;
    v_move_result     JSONB;
    v_checkout_result JSONB;
BEGIN
    SELECT * INTO v_intent
    FROM public.payment_intents
    WHERE id = p_payment_intent_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('success', false, 'error', 'INTENT_NOT_FOUND');
    END IF;

    IF v_intent.status = 'SUCCEEDED' THEN
        RETURN jsonb_build_object('success', true, 'already_settled', true);
    END IF;

    IF v_intent.status <> 'PENDING' THEN
        RETURN jsonb_build_object('success', false, 'error', 'INTENT_NOT_PENDING');
    END IF;

    UPDATE public.payment_intents SET status = 'SUCCEEDED', updated_at = NOW() WHERE id = p_payment_intent_id;

    IF v_intent.purpose = 'TOP_UP' THEN
        v_move_result := public.move_ap(
            v_intent.player_id, v_intent.ap_amount, 'TOP_UP',
            'topup-intent-' || p_payment_intent_id::text, 'payment_intent', p_payment_intent_id
        );

        IF NOT (v_move_result->>'success')::boolean AND v_move_result->>'error' <> 'DUPLICATE_KEY' THEN
            RETURN jsonb_build_object('success', false, 'error', COALESCE(v_move_result->>'error', 'TOP_UP_FAILED'));
        END IF;
    ELSIF v_intent.purpose = 'ORDER' THEN
        BEGIN
            v_checkout_result := public.checkout_order(v_intent.order_id);
        EXCEPTION WHEN OTHERS THEN
            RETURN jsonb_build_object('success', false, 'error', SQLERRM);
        END;
    END IF;

    RETURN jsonb_build_object(
        'success', true,
        'purpose', v_intent.purpose,
        'move_ap', v_move_result,
        'checkout', v_checkout_result
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.clean_expired_orders() RETURNS integer
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    r_order       RECORD;
    r_item        RECORD;
    v_clean_count INTEGER := 0;
BEGIN
    FOR r_order IN
        SELECT id FROM public.orders
        WHERE status = 'PENDING' AND expires_at < NOW()
        FOR UPDATE
    LOOP
        FOR r_item IN
            SELECT variant_id, quantity FROM public.order_items WHERE order_id = r_order.id
        LOOP
            UPDATE public.store_item_variants
            SET reserved_stock = GREATEST(reserved_stock - r_item.quantity, 0)
            WHERE id = r_item.variant_id;
        END LOOP;

        UPDATE public.orders SET status = 'EXPIRED' WHERE id = r_order.id;
        v_clean_count := v_clean_count + 1;
    END LOOP;

    RETURN v_clean_count;
END;
$$;

DROP FUNCTION public.create_store_order(jsonb, uuid, text, text, text);
CREATE OR REPLACE FUNCTION public.create_store_order(p_items_json jsonb, p_address_id uuid DEFAULT NULL::uuid, p_idempotency_key text DEFAULT NULL::text) RETURNS uuid
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    v_player_id      UUID := public.current_player_id();
    v_existing_order UUID;
    v_order_id       UUID;
    v_variant_id     UUID;
    v_qty            INTEGER;
    v_variant        RECORD;
    v_total_ap       INTEGER := 0;
    v_total_thb      INTEGER := 0;
    v_owned_qty      INTEGER;
    v_pending_qty    INTEGER;
BEGIN
    IF v_player_id IS NULL THEN
        RAISE EXCEPTION 'UNAUTHORIZED';
    END IF;

    IF p_idempotency_key IS NOT NULL THEN
        SELECT id INTO v_existing_order
        FROM public.orders
        WHERE idempotency_key = p_idempotency_key AND player_id = v_player_id;

        IF FOUND THEN
            RETURN v_existing_order;
        END IF;
    END IF;

    INSERT INTO public.orders (player_id, status, shipping_address_id, expires_at, idempotency_key)
    VALUES (v_player_id, 'PENDING', p_address_id, NOW() + INTERVAL '15 minutes', p_idempotency_key)
    RETURNING id INTO v_order_id;

    FOR v_variant_id, v_qty IN
        SELECT key::uuid, value::integer FROM jsonb_each_text(p_items_json)
    LOOP
        SELECT v.id, v.stock, v.reserved_stock, v.price_ap, v.price_thb, v.name,
               v.available_until, v.is_active AS variant_is_active,
               i.type AS item_type, i.max_per_player, i.name AS item_name, i.is_active AS item_is_active
        INTO v_variant
        FROM public.store_item_variants v
        JOIN public.store_items i ON i.id = v.item_id
        WHERE v.id = v_variant_id
        FOR UPDATE OF v;

        IF NOT FOUND OR NOT v_variant.variant_is_active OR NOT v_variant.item_is_active THEN
            RAISE EXCEPTION 'ITEM_NOT_AVAILABLE';
        END IF;

        IF v_variant.available_until IS NOT NULL AND v_variant.available_until < NOW() THEN
            RAISE EXCEPTION 'ITEM_NOT_AVAILABLE';
        END IF;

        IF v_variant.item_type = 'PHYSICAL' AND p_address_id IS NULL THEN
            RAISE EXCEPTION 'SHIPPING_ADDRESS_REQUIRED';
        END IF;

        IF (v_variant.stock - v_variant.reserved_stock) < v_qty THEN
            RAISE EXCEPTION 'OUT_OF_STOCK';
        END IF;

        IF v_variant.max_per_player IS NOT NULL THEN
            SELECT COALESCE(SUM(quantity), 0) INTO v_owned_qty
            FROM public.player_inventory
            WHERE player_id = v_player_id AND variant_id = v_variant_id;

            SELECT COALESCE(SUM(oi.quantity), 0) INTO v_pending_qty
            FROM public.order_items oi
            JOIN public.orders o ON o.id = oi.order_id
            WHERE oi.variant_id = v_variant_id
              AND o.player_id = v_player_id
              AND o.status = 'PENDING';

            IF v_owned_qty + v_pending_qty + v_qty > v_variant.max_per_player THEN
                RAISE EXCEPTION 'MAX_LIMIT_REACHED';
            END IF;
        END IF;

        UPDATE public.store_item_variants
        SET reserved_stock = reserved_stock + v_qty
        WHERE id = v_variant_id;

        INSERT INTO public.order_items (order_id, variant_id, name_at, unit_price_ap, unit_price_thb, quantity)
        VALUES (v_order_id, v_variant_id, v_variant.item_name || ' - ' || v_variant.name, v_variant.price_ap, v_variant.price_thb, v_qty);

        v_total_ap := v_total_ap + (v_variant.price_ap * v_qty);
        v_total_thb := v_total_thb + (v_variant.price_thb * v_qty);
    END LOOP;

    UPDATE public.orders
    SET total_price_ap = v_total_ap, total_price_thb = v_total_thb
    WHERE id = v_order_id;

    RETURN v_order_id;
END;
$$;

-- 2) drop functions added by A3
DROP FUNCTION public.fulfill_paid_order(uuid, uuid);
DROP FUNCTION public.prepare_order_fiat_intent(uuid, uuid, timestamptz);
DROP FUNCTION public.preview_store_coupon(text, text, text, integer);
DROP FUNCTION public._store_fulfill_order(uuid);

-- 3) grants as live before A3 (Hotfix 1 + Hotfix 2)
REVOKE ALL ON FUNCTION public.checkout_order(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.checkout_order(uuid) TO authenticated, service_role;
REVOKE ALL ON FUNCTION public.create_store_order(jsonb, uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_store_order(jsonb, uuid, text) TO authenticated, service_role;
REVOKE ALL ON FUNCTION public.settle_payment_intent(uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.settle_payment_intent(uuid) TO service_role;
REVOKE ALL ON FUNCTION public.clean_expired_orders() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.clean_expired_orders() TO service_role;

-- 4) restore the 2 coupon policies
CREATE POLICY "Partner Coop Manage Own Coupons" ON public.partner_coupons USING ((EXISTS ( SELECT 1
   FROM public.sponsors s
  WHERE ((s.id = partner_coupons.sponsor_id) AND (s.partner_player_id IN ( SELECT players.id
           FROM public.players
          WHERE (players.user_id = auth.uid()))) AND (s.tier = 'PARTNER_COOP'::public.sponsor_tier) AND (s.status = 'APPROVED'::public.sponsor_status)))));

CREATE POLICY "Public Read Active Coupons" ON public.partner_coupons FOR SELECT USING (((is_active = true) AND (expires_at > now()) AND (current_uses < max_total_uses)));

-- 5) drop columns/constraints added by A3 (dependent CHECKs and indexes drop with their columns)
ALTER TABLE public.partner_coupon_redemptions
    DROP COLUMN order_id, DROP COLUMN discount_amount, DROP COLUMN discount_currency, DROP COLUMN released_at;
ALTER TABLE public.orders
    DROP COLUMN coupon_id, DROP COLUMN storefront_id, DROP COLUMN payment_method,
    DROP COLUMN subtotal_ap, DROP COLUMN subtotal_thb, DROP COLUMN discount_ap, DROP COLUMN discount_thb;
ALTER TABLE public.partner_coupons
    DROP COLUMN issuer_type, DROP COLUMN storefront_id, DROP COLUMN discount_currency,
    DROP COLUMN discount_amount, DROP COLUMN min_purchase_amount, DROP COLUMN created_by;
ALTER TABLE public.partner_coupons ALTER COLUMN ap_discount_amount DROP DEFAULT;
ALTER TABLE public.partner_coupons ALTER COLUMN sponsor_id SET NOT NULL;

-- 6) payment_intents status (fails if any row is SUCCEEDED_UNFULFILLED - resolve those rows first)
ALTER TABLE public.payment_intents DROP CONSTRAINT payment_intents_status_check;
ALTER TABLE public.payment_intents ADD CONSTRAINT payment_intents_status_check
    CHECK (status = ANY (ARRAY['PENDING'::text, 'SUCCEEDED'::text, 'FAILED'::text, 'EXPIRED'::text]));

-- 7) drop the A3 backup table so A3 can be re-run after rollback
DROP TABLE zbackup.orders_20260929;

NOTIFY pgrst, 'reload schema';
COMMIT;
