-- ROLLBACK of A4 · do NOT place in supabase/migrations
-- Source: Vault 01_BRIEFS_SENT/MASTER_SPEC_Commerce_Hub_PhaseA_2026-09-29.md (section 6)
-- Generated by Alich from the spec text (byte-copy, no retyping) · run by พี่หยัด only (G4)
-- Rollback: none
BEGIN;
SET LOCAL lock_timeout = '3s';
-- If the Luminary data seed (A4b) was run, roll that back FIRST: rows in the new slots would violate the old CHECK.
UPDATE public.sponsor_banners sb SET is_active = b.is_active, updated_at = b.updated_at
    FROM zbackup.sponsor_banners_20260929 b WHERE b.id = sb.id;
ALTER TABLE public.sponsor_banners DROP CONSTRAINT chk_slot_position;
ALTER TABLE public.sponsor_banners ADD CONSTRAINT chk_slot_position CHECK (((slot_position)::text = ANY ((ARRAY['TOP_LEADERBOARD'::character varying, 'LEFT_TOWER'::character varying, 'RIGHT_TOWER'::character varying])::text[])));
DROP TABLE zbackup.sponsor_banners_20260929;
COMMIT;
