-- ROLLBACK of A2 · do NOT place in supabase/migrations
-- Source: Vault 01_BRIEFS_SENT/MASTER_SPEC_Commerce_Hub_PhaseA_2026-09-29.md (section 6)
-- Generated by Alich from the spec text (byte-copy, no retyping) · run by พี่หยัด only (G4)
-- Rollback: none needed
BEGIN;
UPDATE public.store_items s SET is_active = b.is_active FROM zbackup.store_items_20260929 b WHERE b.id = s.id;
ALTER TABLE public.store_items DROP COLUMN brand_id, DROP COLUMN storefront_id;
ALTER TABLE public.store_categories DROP COLUMN brand_id, DROP COLUMN storefront_id;
DROP TABLE public.brands;
DROP TABLE public.storefronts;
DROP TABLE zbackup.store_items_20260929, zbackup.store_categories_20260929;  -- v1.3: ให้รัน A2 ซ้ำได้หลังย้อนกลับ
COMMIT;
