-- Commerce Hub Phase A · A2 · storefronts + brands
-- Source: Vault 01_BRIEFS_SENT/MASTER_SPEC_Commerce_Hub_PhaseA_2026-09-29.md (section 6)
-- Generated by Alich from the spec text (byte-copy, no retyping) · run by พี่หยัด only (G4)
-- Rollback: supabase/rollbacks/20260929100100_commerce_a2_rollback.sql
BEGIN;
SET LOCAL lock_timeout = '3s';

-- สำรองข้อมูลเดิม (schema นี้ API มองไม่เห็น)
CREATE SCHEMA IF NOT EXISTS zbackup;
REVOKE ALL ON SCHEMA zbackup FROM PUBLIC, anon, authenticated;
CREATE TABLE zbackup.store_items_20260929 AS SELECT * FROM public.store_items;
CREATE TABLE zbackup.store_categories_20260929 AS SELECT * FROM public.store_categories;

CREATE TABLE public.storefronts (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    slug text NOT NULL UNIQUE,
    name text NOT NULL,
    allow_ap_payment boolean NOT NULL DEFAULT false,
    allow_fiat_payment boolean NOT NULL DEFAULT true,
    require_athlete_profile boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_storefront_has_payment CHECK (allow_ap_payment OR allow_fiat_payment)
);

CREATE TABLE public.brands (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    slug text NOT NULL UNIQUE,
    name text NOT NULL,
    logo_url text,
    badge_icon text,
    sponsor_id uuid REFERENCES public.sponsors(id) ON DELETE SET NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_brand_logo_https CHECK (logo_url IS NULL OR logo_url LIKE 'https://%')
);
CREATE INDEX idx_brands_sponsor_id ON public.brands (sponsor_id);

CREATE TRIGGER trg_storefronts_updated_at BEFORE UPDATE ON public.storefronts
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_brands_updated_at BEFORE UPDATE ON public.brands
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- P1-1: RLS ตั้งแต่ก้อนแรก · อ่านได้เฉพาะ active · ไม่มี policy เขียน = เขียนได้แค่ service role (route แอดมินกั้นด้วย requireAdminRole)
ALTER TABLE public.storefronts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;
CREATE POLICY storefronts_public_select ON public.storefronts FOR SELECT TO anon, authenticated USING (is_active);
CREATE POLICY brands_public_select ON public.brands FOR SELECT TO anon, authenticated USING (is_active);

INSERT INTO public.storefronts (slug, name, allow_ap_payment, allow_fiat_payment, require_athlete_profile)
VALUES ('zodiac-esports', 'Zodiac Arena Esports Store', true, true, true);

-- D10: SINOPEC = แบรนด์ธรรมดา ไม่ผูกสปอนเซอร์
INSERT INTO public.brands (slug, name, badge_icon) VALUES ('sinopec', 'SINOPEC', '🛢️');

ALTER TABLE public.store_items
    ADD COLUMN storefront_id uuid REFERENCES public.storefronts(id),
    ADD COLUMN brand_id uuid REFERENCES public.brands(id) ON DELETE SET NULL;
ALTER TABLE public.store_categories
    ADD COLUMN storefront_id uuid REFERENCES public.storefronts(id),
    ADD COLUMN brand_id uuid REFERENCES public.brands(id) ON DELETE SET NULL;
CREATE INDEX idx_store_items_storefront ON public.store_items (storefront_id);
CREATE INDEX idx_store_items_brand ON public.store_items (brand_id);

UPDATE public.store_items SET storefront_id = (SELECT id FROM public.storefronts WHERE slug = 'zodiac-esports');
UPDATE public.store_categories SET storefront_id = (SELECT id FROM public.storefronts WHERE slug = 'zodiac-esports');
UPDATE public.store_items SET brand_id = (SELECT id FROM public.brands WHERE slug = 'sinopec')
    WHERE upper(partner_brand) = 'SINOPEC';
UPDATE public.store_categories SET brand_id = (SELECT id FROM public.brands WHERE slug = 'sinopec')
    WHERE upper(partner_brand) = 'SINOPEC';

-- D10 / Q0: ปิดขายสินค้า SINOPEC (ไม่ใช่พาร์ตเนอร์)
UPDATE public.store_items SET is_active = false WHERE brand_id = (SELECT id FROM public.brands WHERE slug = 'sinopec');

COMMIT;
