-- Commerce Hub Phase A · A3 · payment path + coupons (closes P0-1..5)
-- Source: Vault 01_BRIEFS_SENT/MASTER_SPEC_Commerce_Hub_PhaseA_2026-09-29.md (section 6)
-- Generated by Alich from the spec text (byte-copy, no retyping) · run by พี่หยัด only (G4)
-- Rollback: supabase/rollbacks/20260929100200_commerce_a3_rollback.sql
BEGIN;
SET LOCAL lock_timeout = '3s';

CREATE TABLE zbackup.orders_20260929 AS SELECT * FROM public.orders;

-- ── orders ─────────────────────────────────────────────
ALTER TABLE public.orders
    ADD COLUMN storefront_id uuid REFERENCES public.storefronts(id),
    ADD COLUMN payment_method text,
    ADD COLUMN subtotal_ap integer NOT NULL DEFAULT 0,
    ADD COLUMN subtotal_thb integer NOT NULL DEFAULT 0,
    ADD COLUMN coupon_id uuid REFERENCES public.partner_coupons(id),
    ADD COLUMN discount_ap integer NOT NULL DEFAULT 0,
    ADD COLUMN discount_thb integer NOT NULL DEFAULT 0;

-- ออเดอร์เดิม 1 แถวจ่ายด้วย AP (Step 0 ข้อ 5) · ไม่แตะ total เดิม (KR2)
UPDATE public.orders
SET storefront_id = (SELECT id FROM public.storefronts WHERE slug = 'zodiac-esports'),
    payment_method = 'AP',
    subtotal_ap = total_price_ap,
    subtotal_thb = total_price_thb;

ALTER TABLE public.orders
    ALTER COLUMN storefront_id SET NOT NULL,
    ALTER COLUMN payment_method SET NOT NULL,
    ADD CONSTRAINT chk_orders_payment_method CHECK (payment_method IN ('AP', 'FIAT')),
    ADD CONSTRAINT chk_orders_amounts_nonneg CHECK (subtotal_ap >= 0 AND subtotal_thb >= 0 AND discount_ap >= 0 AND discount_thb >= 0),
    ADD CONSTRAINT chk_orders_discount_currency CHECK (
        (payment_method = 'AP' AND discount_thb = 0) OR (payment_method = 'FIAT' AND discount_ap = 0));
CREATE INDEX idx_orders_coupon ON public.orders (coupon_id) WHERE coupon_id IS NOT NULL;

-- ── payment_intents ────────────────────────────────────
ALTER TABLE public.payment_intents DROP CONSTRAINT payment_intents_status_check;
ALTER TABLE public.payment_intents ADD CONSTRAINT payment_intents_status_check
    CHECK (status = ANY (ARRAY['PENDING', 'SUCCEEDED', 'SUCCEEDED_UNFULFILLED', 'FAILED', 'EXPIRED']));

-- ── partner_coupons (Q3 = B · D6 · D11) ─────────────────
ALTER TABLE public.partner_coupons ALTER COLUMN sponsor_id DROP NOT NULL;
ALTER TABLE public.partner_coupons ALTER COLUMN ap_discount_amount SET DEFAULT 0;
ALTER TABLE public.partner_coupons
    ADD COLUMN issuer_type text NOT NULL,
    ADD COLUMN storefront_id uuid NOT NULL REFERENCES public.storefronts(id),
    ADD COLUMN discount_currency text NOT NULL,
    ADD COLUMN discount_amount integer NOT NULL,
    ADD COLUMN min_purchase_amount integer NOT NULL DEFAULT 0,
    ADD COLUMN created_by uuid REFERENCES public.players(id) ON DELETE SET NULL,
    ADD CONSTRAINT chk_coupon_issuer CHECK (
        (issuer_type = 'PLATFORM' AND sponsor_id IS NULL) OR (issuer_type = 'SPONSOR' AND sponsor_id IS NOT NULL)),
    ADD CONSTRAINT chk_coupon_currency CHECK (discount_currency IN ('AP', 'THB')),
    ADD CONSTRAINT chk_coupon_discount_amount CHECK (discount_amount > 0),
    ADD CONSTRAINT chk_coupon_min_purchase CHECK (min_purchase_amount >= 0);
-- (ADD COLUMN ... NOT NULL ไม่มี default จะล้มทันทีถ้าตารางไม่ว่าง = ตัวกันตาม pre-check)

-- P1-2: ปิดช่องพาร์ตเนอร์แก้ current_uses เอง + ปิดการเปิดโชว์รหัสคูปองให้ anon
DROP POLICY "Partner Coop Manage Own Coupons" ON public.partner_coupons;
DROP POLICY "Public Read Active Coupons" ON public.partner_coupons;

ALTER TABLE public.partner_coupon_redemptions
    ADD COLUMN order_id uuid REFERENCES public.orders(id),
    ADD COLUMN discount_amount integer,
    ADD COLUMN discount_currency text,
    ADD COLUMN released_at timestamptz,
    ADD CONSTRAINT chk_redemption_currency CHECK (discount_currency IS NULL OR discount_currency IN ('AP', 'THB'));
CREATE UNIQUE INDEX uq_coupon_redemption_order ON public.partner_coupon_redemptions (order_id) WHERE order_id IS NOT NULL;

-- ── ฟังก์ชันภายใน: ส่งมอบของ + ตั้ง PAID ────────────────
CREATE FUNCTION public._store_fulfill_order(p_order_id uuid) RETURNS integer
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    v_player_id  uuid;
    r_item       record;
    v_store_type varchar;
    v_eq_type    varchar;
    v_count      integer := 0;
BEGIN
    SELECT player_id INTO v_player_id
    FROM public.orders WHERE id = p_order_id AND status = 'PENDING'
    FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'ORDER_NOT_PENDING';
    END IF;

    FOR r_item IN
        SELECT variant_id, quantity, name_at FROM public.order_items WHERE order_id = p_order_id
    LOOP
        UPDATE public.store_item_variants
        SET stock = stock - r_item.quantity,
            reserved_stock = reserved_stock - r_item.quantity
        WHERE id = r_item.variant_id;

        SELECT i.type INTO v_store_type
        FROM public.store_items i
        JOIN public.store_item_variants v ON v.item_id = i.id
        WHERE v.id = r_item.variant_id;

        IF v_store_type = 'DIGITAL' THEN
            v_eq_type := 'FRAME';
            IF POSITION('badge' IN LOWER(r_item.name_at)) > 0 THEN
                v_eq_type := 'BADGE';
            ELSIF POSITION('title' IN LOWER(r_item.name_at)) > 0 THEN
                v_eq_type := 'TITLE';
            END IF;

            INSERT INTO public.player_inventory (player_id, variant_id, item_type, is_equipped, quantity)
            VALUES (v_player_id, r_item.variant_id, v_eq_type, FALSE, r_item.quantity)
            ON CONFLICT (player_id, variant_id) DO UPDATE
                SET quantity = public.player_inventory.quantity + EXCLUDED.quantity;
        ELSIF v_store_type = 'PHYSICAL' THEN
            INSERT INTO public.shipments (order_id, status) VALUES (p_order_id, 'PENDING');
        END IF;

        v_count := v_count + 1;
    END LOOP;

    UPDATE public.orders SET status = 'PAID' WHERE id = p_order_id;
    RETURN v_count;
END;
$$;

-- ── checkout_order: จ่าย AP เท่านั้น (P0-1, P0-3) ────────
CREATE OR REPLACE FUNCTION public.checkout_order(p_order_id uuid) RETURNS jsonb
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    v_caller        uuid := public.current_player_id();
    v_order         record;
    v_allow_ap      boolean;
    v_move_result   jsonb;
    v_balance_after numeric;
    v_count         integer;
BEGIN
    SET LOCAL lock_timeout = '3s';

    IF v_caller IS NULL THEN
        RAISE EXCEPTION 'UNAUTHORIZED';
    END IF;

    SELECT id, player_id, status, total_price_ap, expires_at, payment_method, storefront_id
    INTO v_order
    FROM public.orders WHERE id = p_order_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'ORDER_NOT_FOUND';
    END IF;
    -- Anti-BOLA: เจ้าของเท่านั้น (ไม่มีทางลัดแอดมิน — is_admin() รวม REFEREE)
    IF v_order.player_id IS DISTINCT FROM v_caller THEN
        RAISE EXCEPTION 'FORBIDDEN';
    END IF;
    IF v_order.status <> 'PENDING' THEN
        RAISE EXCEPTION 'ORDER_NOT_PENDING';
    END IF;
    IF v_order.expires_at < NOW() THEN
        RAISE EXCEPTION 'ORDER_EXPIRED';
    END IF;
    IF v_order.payment_method IS DISTINCT FROM 'AP' THEN
        RAISE EXCEPTION 'PAYMENT_METHOD_MISMATCH';
    END IF;

    SELECT allow_ap_payment INTO v_allow_ap
    FROM public.storefronts WHERE id = v_order.storefront_id AND is_active;
    IF v_allow_ap IS NOT TRUE THEN
        RAISE EXCEPTION 'AP_NOT_ALLOWED';
    END IF;

    IF v_order.total_price_ap <= 0 THEN
        RAISE EXCEPTION 'INVALID_ORDER_TOTAL';
    END IF;

    v_move_result := public.move_ap(
        v_order.player_id, -v_order.total_price_ap, 'STORE_REDEEM',
        'checkout-order-' || p_order_id::text, 'order', p_order_id
    );
    IF NOT (v_move_result->>'success')::boolean THEN
        IF v_move_result->>'error' = 'INSUFFICIENT_AP_BALANCE' THEN
            RAISE EXCEPTION 'INSUFFICIENT_AP';
        ELSIF v_move_result->>'error' = 'DUPLICATE_KEY' THEN
            RAISE EXCEPTION 'ORDER_NOT_PENDING';
        ELSE
            RAISE EXCEPTION '%', v_move_result->>'error';
        END IF;
    END IF;
    v_balance_after := (v_move_result->>'balance_after')::numeric;

    v_count := public._store_fulfill_order(p_order_id);

    RETURN jsonb_build_object(
        'success', true,
        'order_id', p_order_id,
        'status', 'PAID',
        'fulfilled_items_count', v_count,
        'ap_deducted', v_order.total_price_ap,          -- ยอดสุทธิหลังคูปอง → cashback คิดจากตัวนี้ (D6)
        'remaining_balance', COALESCE(v_balance_after, 0)
    );
END;
$$;

-- ── fulfill_paid_order: ส่งมอบหลังจ่ายนอก AP (P0-1, P0-2) ──
CREATE FUNCTION public.fulfill_paid_order(p_order_id uuid, p_payment_intent_id uuid) RETURNS jsonb
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    v_intent record;
    v_order  record;
    v_count  integer;
BEGIN
    SET LOCAL lock_timeout = '3s';

    IF auth.role() IS DISTINCT FROM 'service_role' THEN
        RAISE EXCEPTION 'FORBIDDEN';
    END IF;

    SELECT id, order_id, purpose, status, amount_thb INTO v_intent
    FROM public.payment_intents WHERE id = p_payment_intent_id;
    IF NOT FOUND OR v_intent.purpose <> 'ORDER' OR v_intent.order_id IS DISTINCT FROM p_order_id THEN
        RAISE EXCEPTION 'INTENT_ORDER_MISMATCH';
    END IF;
    IF v_intent.status <> 'SUCCEEDED' THEN
        RAISE EXCEPTION 'INTENT_NOT_SUCCEEDED';
    END IF;

    SELECT id, status, payment_method, total_price_thb INTO v_order
    FROM public.orders WHERE id = p_order_id
    FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'ORDER_NOT_FOUND';
    END IF;
    IF v_order.payment_method <> 'FIAT' THEN
        RAISE EXCEPTION 'PAYMENT_METHOD_MISMATCH';
    END IF;
    IF v_order.status <> 'PENDING' THEN
        RAISE EXCEPTION 'ORDER_NOT_PENDING';
    END IF;
    IF v_intent.amount_thb IS NOT NULL AND v_intent.amount_thb <> v_order.total_price_thb THEN
        RAISE EXCEPTION 'AMOUNT_MISMATCH';
    END IF;
    -- ไม่เช็ค expires_at: เงินเข้าแล้ว และออเดอร์ที่ยัง PENDING = สต็อกยังจองอยู่ (clean_expired_orders ข้ามออเดอร์ที่มี intent ค้าง)

    v_count := public._store_fulfill_order(p_order_id);

    RETURN jsonb_build_object('success', true, 'order_id', p_order_id, 'status', 'PAID', 'fulfilled_items_count', v_count);
END;
$$;

-- ── settle_payment_intent: ห้ามเงียบ (P0-2 · D2) ─────────
CREATE OR REPLACE FUNCTION public.settle_payment_intent(p_payment_intent_id uuid) RETURNS jsonb
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    v_intent      record;
    v_move_result jsonb;
    v_fulfill     jsonb;
    v_err         text;
BEGIN
    SET LOCAL lock_timeout = '3s';

    SELECT * INTO v_intent FROM public.payment_intents WHERE id = p_payment_intent_id FOR UPDATE;
    IF NOT FOUND THEN
        RETURN jsonb_build_object('success', false, 'error', 'INTENT_NOT_FOUND');
    END IF;
    IF v_intent.status = 'SUCCEEDED' THEN
        RETURN jsonb_build_object('success', true, 'already_settled', true);
    END IF;
    IF v_intent.status = 'SUCCEEDED_UNFULFILLED' THEN
        RETURN jsonb_build_object('success', false, 'already_settled', true, 'error', 'UNFULFILLED_NEEDS_REVIEW');
    END IF;
    IF v_intent.status <> 'PENDING' THEN
        RETURN jsonb_build_object('success', false, 'error', 'INTENT_NOT_PENDING');
    END IF;

    UPDATE public.payment_intents SET status = 'SUCCEEDED', updated_at = NOW() WHERE id = p_payment_intent_id;

    IF v_intent.purpose = 'TOP_UP' THEN
        v_move_result := public.move_ap(
            v_intent.player_id, v_intent.ap_amount, 'TOP_UP',
            'topup-intent-' || p_payment_intent_id::text, 'payment_intent', p_payment_intent_id
        );
        IF NOT (v_move_result->>'success')::boolean AND v_move_result->>'error' <> 'DUPLICATE_KEY' THEN
            -- ย้อนทั้งก้อน: intent กลับเป็น PENDING · webhook ได้ error → ผู้ให้บริการส่งซ้ำ
            RAISE EXCEPTION 'TOP_UP_FAILED: %', COALESCE(v_move_result->>'error', 'UNKNOWN');
        END IF;
    ELSIF v_intent.purpose = 'ORDER' THEN
        BEGIN
            v_fulfill := public.fulfill_paid_order(v_intent.order_id, p_payment_intent_id);
        EXCEPTION WHEN OTHERS THEN
            v_err := SQLERRM;
            -- เงินเข้าแล้วแต่ส่งมอบไม่ได้ → บันทึกสถานะให้แอดมินเห็นและคืนเงิน
            UPDATE public.payment_intents SET status = 'SUCCEEDED_UNFULFILLED', updated_at = NOW()
            WHERE id = p_payment_intent_id;
            RETURN jsonb_build_object(
                'success', false,
                'error', 'FULFILLMENT_FAILED',
                'detail', v_err,
                'payment_intent_id', p_payment_intent_id,
                'needs_refund_review', true
            );
        END;
    END IF;

    RETURN jsonb_build_object('success', true, 'purpose', v_intent.purpose, 'move_ap', v_move_result, 'fulfill', v_fulfill);
END;
$$;

-- ── create_store_order: เลือกวิธีจ่าย + 1 ร้าน + คูปอง (D1, D4, D6) ──
DROP FUNCTION public.create_store_order(jsonb, uuid, text);

CREATE FUNCTION public.create_store_order(
    p_items_json      jsonb,
    p_address_id      uuid DEFAULT NULL,
    p_idempotency_key text DEFAULT NULL,
    p_payment_method  text DEFAULT 'AP',
    p_coupon_code     text DEFAULT NULL
) RETURNS uuid
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    v_player_id      uuid := public.current_player_id();
    v_existing_order uuid;
    v_order_id       uuid;
    v_sf_ids         uuid[];
    v_storefront_id  uuid;
    v_sf             record;
    v_variant_id     uuid;
    v_qty            integer;
    v_variant        record;
    v_sub_ap         integer := 0;
    v_sub_thb        integer := 0;
    v_subtotal       integer;
    v_owned_qty      integer;
    v_pending_qty    integer;
    v_coupon         record;
    v_coupon_id      uuid;
    v_player_uses    integer;
    v_discount       integer := 0;
BEGIN
    SET LOCAL lock_timeout = '3s';

    IF v_player_id IS NULL THEN
        RAISE EXCEPTION 'UNAUTHORIZED';
    END IF;
    IF p_payment_method IS NULL OR p_payment_method NOT IN ('AP', 'FIAT') THEN
        RAISE EXCEPTION 'INVALID_PAYMENT_METHOD';
    END IF;
    IF p_items_json IS NULL OR jsonb_typeof(p_items_json) <> 'object' OR p_items_json = '{}'::jsonb THEN
        RAISE EXCEPTION 'EMPTY_CART';
    END IF;

    IF p_idempotency_key IS NOT NULL THEN
        SELECT id INTO v_existing_order FROM public.orders
        WHERE idempotency_key = p_idempotency_key AND player_id = v_player_id;
        IF FOUND THEN
            RETURN v_existing_order;
        END IF;
    END IF;

    -- D6: 1 ออเดอร์ = 1 หน้าร้าน
    SELECT array_agg(DISTINCT i.storefront_id) INTO v_sf_ids
    FROM public.store_item_variants v
    JOIN public.store_items i ON i.id = v.item_id
    WHERE v.id IN (SELECT key::uuid FROM jsonb_each_text(p_items_json));

    IF v_sf_ids IS NULL THEN
        RAISE EXCEPTION 'ITEM_NOT_AVAILABLE';
    END IF;
    IF cardinality(v_sf_ids) > 1 THEN
        RAISE EXCEPTION 'MIXED_STOREFRONT';
    END IF;
    v_storefront_id := v_sf_ids[1];
    IF v_storefront_id IS NULL THEN
        RAISE EXCEPTION 'ITEM_NOT_AVAILABLE';
    END IF;

    SELECT * INTO v_sf FROM public.storefronts WHERE id = v_storefront_id AND is_active;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'STOREFRONT_INACTIVE';
    END IF;
    IF (p_payment_method = 'AP' AND NOT v_sf.allow_ap_payment)
       OR (p_payment_method = 'FIAT' AND NOT v_sf.allow_fiat_payment) THEN
        RAISE EXCEPTION 'PAYMENT_METHOD_NOT_ALLOWED';
    END IF;

    INSERT INTO public.orders (player_id, status, shipping_address_id, expires_at, idempotency_key, payment_method, storefront_id)
    VALUES (v_player_id, 'PENDING', p_address_id, NOW() + INTERVAL '15 minutes', p_idempotency_key, p_payment_method, v_storefront_id)
    RETURNING id INTO v_order_id;

    FOR v_variant_id, v_qty IN
        SELECT key::uuid, value::integer FROM jsonb_each_text(p_items_json)
    LOOP
        IF v_qty IS NULL OR v_qty <= 0 THEN
            RAISE EXCEPTION 'INVALID_QUANTITY';
        END IF;

        SELECT v.id, v.stock, v.reserved_stock, v.price_ap, v.price_thb, v.name,
               v.available_until, v.is_active AS variant_is_active,
               i.type AS store_type, i.max_per_player, i.name AS item_name, i.is_active AS item_is_active
        INTO v_variant
        FROM public.store_item_variants v
        JOIN public.store_items i ON i.id = v.item_id
        WHERE v.id = v_variant_id
        FOR UPDATE OF v;

        IF NOT FOUND OR NOT v_variant.variant_is_active OR NOT v_variant.item_is_active THEN
            RAISE EXCEPTION 'ITEM_NOT_AVAILABLE';
        END IF;
        IF v_variant.available_until IS NOT NULL AND v_variant.available_until < NOW() THEN
            RAISE EXCEPTION 'ITEM_NOT_AVAILABLE';
        END IF;
        -- P0-3: ของที่ไม่มีราคาในสกุลที่เลือก ซื้อด้วยสกุลนั้นไม่ได้
        IF (p_payment_method = 'AP' AND v_variant.price_ap <= 0)
           OR (p_payment_method = 'FIAT' AND v_variant.price_thb <= 0) THEN
            RAISE EXCEPTION 'PRICE_NOT_SET_FOR_METHOD';
        END IF;
        IF v_variant.store_type = 'PHYSICAL' AND p_address_id IS NULL THEN
            RAISE EXCEPTION 'SHIPPING_ADDRESS_REQUIRED';
        END IF;
        IF (v_variant.stock - v_variant.reserved_stock) < v_qty THEN
            RAISE EXCEPTION 'OUT_OF_STOCK';
        END IF;

        IF v_variant.max_per_player IS NOT NULL THEN
            SELECT COALESCE(SUM(quantity), 0) INTO v_owned_qty
            FROM public.player_inventory
            WHERE player_id = v_player_id AND variant_id = v_variant_id;

            SELECT COALESCE(SUM(oi.quantity), 0) INTO v_pending_qty
            FROM public.order_items oi
            JOIN public.orders o ON o.id = oi.order_id
            WHERE oi.variant_id = v_variant_id AND o.player_id = v_player_id AND o.status = 'PENDING';

            IF v_owned_qty + v_pending_qty + v_qty > v_variant.max_per_player THEN
                RAISE EXCEPTION 'MAX_LIMIT_REACHED';
            END IF;
        END IF;

        UPDATE public.store_item_variants SET reserved_stock = reserved_stock + v_qty WHERE id = v_variant_id;

        INSERT INTO public.order_items (order_id, variant_id, name_at, unit_price_ap, unit_price_thb, quantity)
        VALUES (v_order_id, v_variant_id, v_variant.item_name || ' - ' || v_variant.name, v_variant.price_ap, v_variant.price_thb, v_qty);

        v_sub_ap := v_sub_ap + (v_variant.price_ap * v_qty);
        v_sub_thb := v_sub_thb + (v_variant.price_thb * v_qty);
    END LOOP;

    v_subtotal := CASE WHEN p_payment_method = 'AP' THEN v_sub_ap ELSE v_sub_thb END;

    -- D4: ใช้คูปองตอนสร้างออเดอร์ (มี session ผู้ใช้จริง) · จองสิทธิ์ใต้ FOR UPDATE
    IF p_coupon_code IS NOT NULL AND btrim(p_coupon_code) <> '' THEN
        SELECT * INTO v_coupon FROM public.partner_coupons
        WHERE code = upper(btrim(p_coupon_code))
        FOR UPDATE;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'COUPON_NOT_FOUND';
        END IF;
        IF NOT v_coupon.is_active OR v_coupon.expires_at <= NOW() THEN
            RAISE EXCEPTION 'COUPON_EXPIRED_OR_INACTIVE';
        END IF;
        IF v_coupon.storefront_id <> v_storefront_id THEN
            RAISE EXCEPTION 'COUPON_NOT_FOR_STOREFRONT';
        END IF;
        IF (p_payment_method = 'AP' AND v_coupon.discount_currency <> 'AP')
           OR (p_payment_method = 'FIAT' AND v_coupon.discount_currency <> 'THB') THEN
            RAISE EXCEPTION 'COUPON_CURRENCY_MISMATCH';
        END IF;
        IF v_coupon.current_uses >= v_coupon.max_total_uses THEN
            RAISE EXCEPTION 'COUPON_MAX_USES_REACHED';
        END IF;
        IF v_subtotal < v_coupon.min_purchase_amount THEN
            RAISE EXCEPTION 'COUPON_MIN_PURCHASE_NOT_MET';
        END IF;
        IF v_coupon.issuer_type = 'SPONSOR' AND NOT EXISTS (
            SELECT 1 FROM public.sponsors s
            WHERE s.id = v_coupon.sponsor_id AND s.status = 'APPROVED' AND s.is_active AND s.tier = 'PARTNER_COOP'
        ) THEN
            RAISE EXCEPTION 'SPONSOR_SUSPENDED_OR_INACTIVE';
        END IF;

        SELECT COUNT(*) INTO v_player_uses FROM public.partner_coupon_redemptions
        WHERE coupon_id = v_coupon.id AND player_id = v_player_id AND released_at IS NULL;
        IF v_player_uses >= v_coupon.per_user_limit THEN
            RAISE EXCEPTION 'USER_REACHED_PER_USER_LIMIT';
        END IF;

        v_discount := LEAST(v_coupon.discount_amount, v_subtotal - 1);   -- I2: ยอดสุทธิ ≥ 1
        IF v_discount <= 0 THEN
            RAISE EXCEPTION 'COUPON_NOT_APPLICABLE';
        END IF;

        UPDATE public.partner_coupons SET current_uses = current_uses + 1, updated_at = NOW() WHERE id = v_coupon.id;

        INSERT INTO public.partner_coupon_redemptions
            (coupon_id, player_id, order_id, discount_applied_ap, discount_amount, discount_currency, idempotency_key)
        VALUES
            (v_coupon.id, v_player_id, v_order_id,
             CASE WHEN p_payment_method = 'AP' THEN v_discount ELSE 0 END,
             v_discount, v_coupon.discount_currency, 'order-coupon-' || v_order_id::text);

        v_coupon_id := v_coupon.id;
    END IF;

    UPDATE public.orders
    SET subtotal_ap     = v_sub_ap,
        subtotal_thb    = v_sub_thb,
        coupon_id       = v_coupon_id,
        discount_ap     = CASE WHEN p_payment_method = 'AP' THEN v_discount ELSE 0 END,
        discount_thb    = CASE WHEN p_payment_method = 'FIAT' THEN v_discount ELSE 0 END,
        total_price_ap  = CASE WHEN p_payment_method = 'AP' THEN v_sub_ap - v_discount ELSE 0 END,
        total_price_thb = CASE WHEN p_payment_method = 'FIAT' THEN v_sub_thb - v_discount ELSE 0 END
    WHERE id = v_order_id;

    RETURN v_order_id;
END;
$$;

-- ── clean_expired_orders: คืนสต็อก + คืนสิทธิ์คูปอง + ข้ามออเดอร์ที่มี intent ค้าง ──
CREATE OR REPLACE FUNCTION public.clean_expired_orders() RETURNS integer
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    r_order       record;
    r_item        record;
    v_clean_count integer := 0;
BEGIN
    FOR r_order IN
        SELECT o.id FROM public.orders o
        WHERE o.status = 'PENDING' AND o.expires_at < NOW()
          AND NOT EXISTS (
              SELECT 1 FROM public.payment_intents pi
              WHERE pi.order_id = o.id AND pi.status = 'PENDING' AND pi.expires_at > NOW())
        FOR UPDATE OF o SKIP LOCKED
    LOOP
        FOR r_item IN
            SELECT variant_id, quantity FROM public.order_items WHERE order_id = r_order.id
        LOOP
            UPDATE public.store_item_variants
            SET reserved_stock = GREATEST(reserved_stock - r_item.quantity, 0)
            WHERE id = r_item.variant_id;
        END LOOP;

        UPDATE public.partner_coupons c
        SET current_uses = GREATEST(c.current_uses - 1, 0), updated_at = NOW()
        FROM public.partner_coupon_redemptions r
        WHERE r.order_id = r_order.id AND r.released_at IS NULL AND c.id = r.coupon_id;

        UPDATE public.partner_coupon_redemptions SET released_at = NOW()
        WHERE order_id = r_order.id AND released_at IS NULL;

        UPDATE public.orders SET status = 'EXPIRED' WHERE id = r_order.id;
        v_clean_count := v_clean_count + 1;
    END LOOP;

    RETURN v_clean_count;
END;
$$;

-- ── prepare_order_fiat_intent: อายุออเดอร์ ≥ intent (D3) ───
CREATE FUNCTION public.prepare_order_fiat_intent(p_order_id uuid, p_player_id uuid, p_intent_expires_at timestamptz)
RETURNS jsonb
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    v_order   record;
    v_new_exp timestamptz;
BEGIN
    SET LOCAL lock_timeout = '3s';

    IF auth.role() IS DISTINCT FROM 'service_role' THEN
        RAISE EXCEPTION 'FORBIDDEN';
    END IF;

    SELECT id, player_id, status, expires_at, payment_method, total_price_thb INTO v_order
    FROM public.orders WHERE id = p_order_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('success', false, 'error', 'ORDER_NOT_FOUND');
    END IF;
    IF v_order.player_id IS DISTINCT FROM p_player_id THEN
        RETURN jsonb_build_object('success', false, 'error', 'FORBIDDEN');
    END IF;
    IF v_order.status <> 'PENDING' THEN
        RETURN jsonb_build_object('success', false, 'error', 'ORDER_NOT_PENDING');
    END IF;
    IF v_order.expires_at < NOW() THEN
        RETURN jsonb_build_object('success', false, 'error', 'ORDER_EXPIRED');
    END IF;
    IF v_order.payment_method <> 'FIAT' THEN
        RETURN jsonb_build_object('success', false, 'error', 'PAYMENT_METHOD_MISMATCH');
    END IF;
    IF v_order.total_price_thb <= 0 THEN
        RETURN jsonb_build_object('success', false, 'error', 'INVALID_ORDER_TOTAL');
    END IF;
    IF p_intent_expires_at IS NULL OR p_intent_expires_at <= NOW() OR p_intent_expires_at > NOW() + INTERVAL '2 hours' THEN
        RETURN jsonb_build_object('success', false, 'error', 'INVALID_INTENT_EXPIRY');
    END IF;

    v_new_exp := GREATEST(v_order.expires_at, p_intent_expires_at + INTERVAL '5 minutes');
    UPDATE public.orders SET expires_at = v_new_exp WHERE id = p_order_id;

    RETURN jsonb_build_object('success', true, 'total_price_thb', v_order.total_price_thb, 'order_expires_at', v_new_exp);
END;
$$;

-- ── preview_store_coupon: ดูส่วนลดก่อนสั่ง (อ่านอย่างเดียว) ──
CREATE FUNCTION public.preview_store_coupon(p_code text, p_storefront_slug text, p_payment_method text, p_subtotal integer)
RETURNS jsonb
    LANGUAGE plpgsql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    v_player_id uuid := public.current_player_id();
    v_sf_id     uuid;
    v_c         record;
    v_uses      integer;
    v_discount  integer;
BEGIN
    IF v_player_id IS NULL THEN
        RETURN jsonb_build_object('success', false, 'error', 'UNAUTHORIZED');
    END IF;
    IF p_code IS NULL OR p_payment_method NOT IN ('AP', 'FIAT') OR p_subtotal IS NULL OR p_subtotal <= 0 THEN
        RETURN jsonb_build_object('success', false, 'error', 'INVALID_INPUT');
    END IF;

    SELECT id INTO v_sf_id FROM public.storefronts WHERE slug = p_storefront_slug AND is_active;
    IF NOT FOUND THEN
        RETURN jsonb_build_object('success', false, 'error', 'STOREFRONT_INACTIVE');
    END IF;

    SELECT * INTO v_c FROM public.partner_coupons WHERE code = upper(btrim(p_code));
    IF NOT FOUND THEN
        RETURN jsonb_build_object('success', false, 'error', 'COUPON_NOT_FOUND');
    END IF;
    IF NOT v_c.is_active OR v_c.expires_at <= NOW() THEN
        RETURN jsonb_build_object('success', false, 'error', 'COUPON_EXPIRED_OR_INACTIVE');
    END IF;
    IF v_c.storefront_id <> v_sf_id THEN
        RETURN jsonb_build_object('success', false, 'error', 'COUPON_NOT_FOR_STOREFRONT');
    END IF;
    IF (p_payment_method = 'AP' AND v_c.discount_currency <> 'AP')
       OR (p_payment_method = 'FIAT' AND v_c.discount_currency <> 'THB') THEN
        RETURN jsonb_build_object('success', false, 'error', 'COUPON_CURRENCY_MISMATCH');
    END IF;
    IF v_c.current_uses >= v_c.max_total_uses THEN
        RETURN jsonb_build_object('success', false, 'error', 'COUPON_MAX_USES_REACHED');
    END IF;
    IF p_subtotal < v_c.min_purchase_amount THEN
        RETURN jsonb_build_object('success', false, 'error', 'COUPON_MIN_PURCHASE_NOT_MET');
    END IF;
    IF v_c.issuer_type = 'SPONSOR' AND NOT EXISTS (
        SELECT 1 FROM public.sponsors s
        WHERE s.id = v_c.sponsor_id AND s.status = 'APPROVED' AND s.is_active AND s.tier = 'PARTNER_COOP'
    ) THEN
        RETURN jsonb_build_object('success', false, 'error', 'SPONSOR_SUSPENDED_OR_INACTIVE');
    END IF;

    SELECT COUNT(*) INTO v_uses FROM public.partner_coupon_redemptions
    WHERE coupon_id = v_c.id AND player_id = v_player_id AND released_at IS NULL;
    IF v_uses >= v_c.per_user_limit THEN
        RETURN jsonb_build_object('success', false, 'error', 'USER_REACHED_PER_USER_LIMIT');
    END IF;

    v_discount := LEAST(v_c.discount_amount, p_subtotal - 1);
    IF v_discount <= 0 THEN
        RETURN jsonb_build_object('success', false, 'error', 'COUPON_NOT_APPLICABLE');
    END IF;

    RETURN jsonb_build_object('success', true, 'discount_amount', v_discount,
                              'discount_currency', v_c.discount_currency, 'title', v_c.title);
END;
$$;

-- ── สิทธิ์ (บังคับทุกฟังก์ชัน) ────────────────────────────
REVOKE ALL ON FUNCTION public._store_fulfill_order(uuid) FROM PUBLIC, anon, authenticated, service_role;

REVOKE ALL ON FUNCTION public.checkout_order(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.checkout_order(uuid) TO authenticated, service_role;

REVOKE ALL ON FUNCTION public.fulfill_paid_order(uuid, uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.fulfill_paid_order(uuid, uuid) TO service_role;

REVOKE ALL ON FUNCTION public.settle_payment_intent(uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.settle_payment_intent(uuid) TO service_role;

REVOKE ALL ON FUNCTION public.create_store_order(jsonb, uuid, text, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_store_order(jsonb, uuid, text, text, text) TO authenticated, service_role;

REVOKE ALL ON FUNCTION public.clean_expired_orders() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.clean_expired_orders() TO service_role;

REVOKE ALL ON FUNCTION public.prepare_order_fiat_intent(uuid, uuid, timestamptz) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.prepare_order_fiat_intent(uuid, uuid, timestamptz) TO service_role;

REVOKE ALL ON FUNCTION public.preview_store_coupon(text, text, text, integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.preview_store_coupon(text, text, text, integer) TO authenticated, service_role;

NOTIFY pgrst, 'reload schema';
COMMIT;
