-- Commerce Hub Phase A · A1 · add MARKETING_ADMIN (run alone, not inside another transaction)
-- Source: Vault 01_BRIEFS_SENT/MASTER_SPEC_Commerce_Hub_PhaseA_2026-09-29.md (section 6)
-- Generated by Alich from the spec text (byte-copy, no retyping) · run by พี่หยัด only (G4)
-- Rollback: none needed
ALTER TYPE public.user_role_type ADD VALUE IF NOT EXISTS 'MARKETING_ADMIN';
