-- Commerce Hub Phase A · A4 · placement registry (7 slots) + archive TOP_LEADERBOARD/RIGHT_TOWER rows (stats kept)
-- Source: Vault 01_BRIEFS_SENT/MASTER_SPEC_Commerce_Hub_PhaseA_2026-09-29.md (section 6)
-- Generated by Alich from the spec text (byte-copy, no retyping) · run by พี่หยัด only (G4)
-- Rollback: supabase/rollbacks/20260929100300_commerce_a4_rollback.sql
BEGIN;
SET LOCAL lock_timeout = '3s';
CREATE TABLE zbackup.sponsor_banners_20260929 AS SELECT * FROM public.sponsor_banners;

ALTER TABLE public.sponsor_banners DROP CONSTRAINT chk_slot_position;
ALTER TABLE public.sponsor_banners ADD CONSTRAINT chk_slot_position CHECK (slot_position IN (
    'TOP_LEADERBOARD', 'LEFT_TOWER', 'RIGHT_TOWER', 'OFFICIAL_SPONSORS_BAR',
    'OBS_SPONSOR_BADGE', 'STREAM_HUB_BOX', 'SPONSOR_LANDING_HERO'));

-- Q1 = B: archive แบนเนอร์ SINOPEC · D7: RIGHT_TOWER เป็น house content → archive แถว DB · สถิติคงเดิม
UPDATE public.sponsor_banners SET is_active = false, updated_at = NOW()
WHERE slot_position IN ('TOP_LEADERBOARD', 'RIGHT_TOWER');
COMMIT;
